# Build library and push to NPM

image: node:7.10

cache:
  paths:
  - node_modules/

stages:
    - compile

compile:
  stage: compile
  script:
    - npm install
    - npm run lint
    - npm run unittest
    - npm prune --prod
    - rm lib/*.spec.* || true
    - npm pack
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
