# Build library and push to NPM

image: node:10

stages:
    - compile

compile:
  stage: compile
  only:
    - master
  script:
    - echo ${NPM_TOKEN} > .npmrc

    - npm install
    - npm run lint
    - npm run build
    - npm run unittest
    - npm publish

