# Build library and push to NPM

image: node:7.10

cache:
  paths:
  - node_modules/

stages:
    - compile

compile:
  stage: compile
  script:
    - npm install
    - npm run lint
    - npm run unittest
    - rm lib/*.spec.* || true
    - npm pack
    - echo ${NPM_TOKEN} > .npmrc
    - npm publish || true
