# Build library and push to NPM

image: node:8.1

cache:
  paths:
    - node_modules/

stages:
    - compile

compile:
  stage: compile
  script:
    - echo ${NPM_TOKEN} > .npmrc

    - npm install
    - npm run lint
    - npm run build
    - npm run unittest
    - npm publish

